### ISSUE TITLE
electron加载自己的react+next应用，out/index.html路径报错问题

### ISSUE THREAD

**Issue by ariel-chenchenchen** [observerkei/blog-observerkei#1]
你好，我现在也在尝试用electron加载自己的react+next应用，跟着您的文章上介绍的步骤
electron加载自己的react+next应用，main.js入口文件的：
 // 适配开发模式和运行模式的不同路径
  if (!app.isPackaged) {
    win.loadFile('out/index.html') 
  } else {
    win.loadFile(path.join(process.resourcesPath, "index.html"));
  }
这个out/index.html路径是找不到的，想问一下这个out是什么目录呢，我的应用中并没有这个目录，能否具体说明一下，感谢

**Comment by observerkei** [comment]
这是因为静态导出不支持 generateStaticParams 动态路由功能，你提供的报错中 [appid] 这种路由方式是动态路由： https://nextjs.net.cn/docs/pages/building-your-application/deploying/static-exports

文章使用了Next.js静态导出的方法来运行项目，因此Next.js只能使用客户端路由，如果要用到服务器路由，考虑到改动量的大小，你可以参考一下这个其他人已经验证过的方法： https://github.com/spa5k/nextjs_approuter_electron  
这是问题链接：https://github.com/vercel/next.js/discussions/28243

**Comment by observerkei** [comment]
已在同一文章中添加 Next.js 动态路由构建方法。

**Comment by observerkei** [comment]
@chenchen-leaner
